### PR TITLE
Rework Label Input

### PR DESCRIPTION
**Pull request by SarcevicAntonio**
- [x] tweak for mobile
- [x] tweak input
  - [x] play with font
  - [x] make it more inputty when unfocused

Addressing some of script racoons feedback.

Make label more prominent with icon and font size increment.

When in focus, input floats and gets as much space as its needs.
$
image
image

### CODE REVIEW

**Comment by paoloricciuti** [comment]
@SarcevicAntonio why the change in font when focused? It seems a bit abrupt. I would probably keep the same font in both status.

Also what do you think of making the input more "inputty" even in unfocused mode so that more people will understand it's an input?

**Comment by SarcevicAntonio** [comment]
I change the font because of how the input sizing works it only works very good on monospace fonts, but they do take more space, so this is the best compromise i tired so far.
I can try adding other fonts that work for both? :shrug: 

Will make it more inputty o7

**Comment by paoloricciuti** [comment]
> I change the font because of how the input sizing works it only works very good on monospace fonts, but they do take more space, so this is the best compromise i tired so far. I can try adding other fonts that work for both? 🤷
> 
> Will make it more inputty o7

What if we use monospace for both and maybe keep the font size a bit smaller?

**Comment by SarcevicAntonio** [comment]
I will maybe rework it again when adding the menu bar. For now this has to do 😅

**Pull request merged**
