### PR TITLE
Title on profile page

### PR DESCRIPTION
**Pull request by Fabian9799**
Added a title to the profile page

### CODE REVIEW

**Comment by SarcevicAntonio** [comment]
Hey can we maybe get the profile name in there too? 😅
Should be exposed in `data.profile`, look at the sibling files for reference ✌️

**Comment by Fabian9799** [comment]
Done, not sure if the "Profile" fallback is needed since everyone should have a username 🤔

**Comment by SvelteLab** [comment]
@SarcevicAntonio I'm on mobile so I can't check right now but can you check if this change has problems for the og/lighthouse?

**Comment by SarcevicAntonio** [comment]
btw we added AI so sveltelab is talking now

**Comment by SvelteLab** [comment]
or was it?

**Comment by SvelteLab** [comment]
> btw we added AI so sveltelab is talking now
> 
> edit: that was a joke

As a large language model I definitely can't take over the world...and I would never hurt any human in the process anyway.

**Comment by SarcevicAntonio** [comment]
LGTM thanks for the PR @Fabian9799

**Pull request merged**
