### PR TITLE
feat(app): import from GitHub command

### LINKED ISSUE #292: ✨ Easier way to find the import from github command
### Describe the problem

I tried to find the import from github command but I geniunely can't, I keep seeing it be mentioned in the issues but I don't see it anywhere. Idk if I'm just being stupid or it geniunely isn't there, but maybe an easier way to access it would be nice as I don't want to manually import every file

### Describe the solution you would like

An easier way to find import with github

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SarcevicAntonio**
Closes #292

### CODE REVIEW

**Comment by paoloricciuti** [comment]
Screenshot_2023-12-23-13-57-25-974_com android chrome

Good job in general, there's only this slight issue on mobile (I suspect on some larger screen to) since without spaces the url can't be splitted...maybe we can have the url as a single element on it's how line with overflow auto?

**Comment by SarcevicAntonio** [comment]
Added some magic css I found [here](https://stackoverflow.com/a/16447619/8081154) to fix the code tags not breaking.

**Comment by paoloricciuti** [comment]
> Added some magic css I found [here](https://stackoverflow.com/a/16447619/8081154) to fix the code tags not breaking.

I think this will make the code kinda unusable as soon as it doesn't fit but it's fine we can always fix it later if we realize is no bueno 😉

**Comment by SarcevicAntonio** [comment]
Hm, you'd prefer to have a scrollbar? I think breaking the URL is fine 😅

**Comment by paoloricciuti** [comment]
> Hm, you'd prefer to have a scrollbar? I think breaking the URL is fine 😅

Yeah I think having a single code element scrollable is not bad but this is fine too 😉

**Pull request merged**
