### PR TITLE
feat: share with open files

### PR DESCRIPTION
**Pull request by paoloricciuti**
Add the ability to share the code together with the open tabs.

I don't particularly like the long name for "**Share code snapshot (with open files)**" maybe we can come up with something else...ideas?

Might also be worth add a test for this...I'm pretty busy tomorrow but let's see how it goes

### CODE REVIEW

**Comment by SarcevicAntonio** [comment]
I feel like maybe we should always share the current tab via a query param, kinda like on Stackblitz.

**Comment by paoloricciuti** [comment]
> I feel like maybe we should always share the current tab via a query param, kinda like on Stackblitz.

I don't know, I would like to share all the files needed and that can get quite messy if you have too much file opens.

Only the open tab could be good too tho...kinda thorned

**Comment by paoloricciuti** [comment]
> maybe we share the current tab by defaut via param and then you have the option to share every opened tab via this menu option? 🤔 idk

So basically in the quick share just share the current tab and in the menu ability to share everything?

**Comment by SarcevicAntonio** [comment]
If by quick share you mean the url in the url bar then yes 😁

**Comment by paoloricciuti** [comment]
> If by quick share you mean the url in the url bar then yes 😁

Ohhhhh gotcha...mmm let me think about this

**Comment by SarcevicAntonio** [comment]
I'd say lets simplify down to just one share command. There would be no need for a header dropdown. Just a share icon button that just opens the command directly, removing the need for the extra click. This also fixes a bug where the share project button in header doesn't work for projects that where _just_ saved without reload, (because the `commands_to_return.push` doesn't rerun).

I'd also love to take space to explain a bit more what the choices are (ID/Hash). I had some phrasing examples [in my mockups](https://github.com/SvelteLab/SvelteLab/assets/6685200/41ec572f-5e18-4870-92cd-b0164769b98f).

The Share button should have `.action-confirm` and the other buttons also should have fitting design to that (could also just have the same class).

For bonus swagness we could show the icons for the files in the selection.

I can make these adjustmens as well if you'd like 😁

**Comment by paoloricciuti** [comment]
> I'd say lets simplify down to just one share command. There would be no need for a header dropdown. Just a share icon button that just opens the command directly, removing the need for the extra click. This also fixes a bug where the share project button in header doesn't work for projects that where _just_ saved without reload, (because the `commands_to_return.push` doesn't rerun).

I actually tought about that but than decided to still have the dropdown and have the correct option being preselected which i feel it's a small but good UX improvement.  But i'm willing to forgo that.

> I'd also love to take space to explain a bit more what the choices are (ID/Hash). I had some phrasing examples [in my mockups](https://github.com/SvelteLab/SvelteLab/assets/6685200/41ec572f-5e18-4870-92cd-b0164769b98f).

This can very well be under the selection, i like it.

> The Share button should have `.action-confirm` and the other buttons also should have fitting design to that (could also just have the same class).

Uh i completely missed that global class, i guess it's the risk of global styles.

> For bonus swagness we could show the icons for the files in the selection.

Uhhh i like this too, didn't tought of this.

> I can make these adjustmens as well if you'd like 😁

I will probably not be able to work on this anymore today so if you want go ahead so that we can close this 😄

**Comment by SarcevicAntonio** [comment]
> I actually tought about that but than decided to still have the dropdown and have the correct option being preselected which i feel it's a small but good UX improvement. But i'm willing to forgo that.

fair, but i see it as an extra click that brings no extra value. people can choose the share way in the action component. maybe instead of a radio toggle it could be two buttons that then directly share the corresponding link so have one click less even

> Uh i completely missed that global class, i guess it's the risk of global styles.

Good thing we have code reviews :)

> so if you want go ahead so that we can close this 😄

🫡

**Comment by SarcevicAntonio** [comment]
This is what I landed on:

Screenshot 2023-08-20 at 19 41 50


Screenshot 2023-08-20 at 19 41 23

Screenshot 2023-08-20 at 19 41 39

**Comment by paoloricciuti** [comment]
I'd say we can go ahead and merge like this

**Pull request merged**
