### PR TITLE
Add throttle and debounce editor preferences

### PR DESCRIPTION
**Pull request by paoloricciuti**
@SarcevicAntonio this adds the ability to customize the delay function and duration for the editor.

- i've renamed the 'Font preferences' command to 'Editor preferences'
- I've added a section for the editor and renamed the old Editor section as Font
- i just now realized we already had a editor_config_store. I'm thorned tho because i feel like this could be changed in small increments and if we stick everything inside the editor config it will reload the extension everytime (because the other one is for Vim and code wrap)...what do you think about this? Should we stick to a single store or split it?
-  i've setup the default to 300ms of throttle because i think it's a bit better for our use case but i'm willing to be conviced of something else 😄 

**EDIT IMPORTANT**

we have to wait for puru to accept my pr and publish a new version before we can merge this. I fucked up sorry

### CODE REVIEW

**Comment by SarcevicAntonio** [comment]
I'm not sure we want to expose these settings to the users. What is the benifit or why would a user change it?

**Comment by paoloricciuti** [comment]
> I'm not sure we want to expose these settings to the users. What is the benifit or why would a user change it?

I don't see why not...one might prefer to constantly have what is writing come up within the preview, some others might want to have it only when they finish writing. Also someone might prefer have it nearly instant and someone wlse might want to wait a lot before seeing the results.

And given that most people are already familiar with that i'd say it's no harm including it

**Comment by SarcevicAntonio** [comment]
Alright fair enoug. Can we make it a separate action component tho? I think that would be better for discoverability. I get that they are related but people searching for font options might not know they are inside editor settings.

As for having it in a single store, i don't think it matters that much, as you don't constantly change it during use, or is it really noticable?

**Comment by paoloricciuti** [comment]
> Alright fair enoug. Can we make it a separate action component tho? I think that would be better for discoverability. I get that they are related but people searching for font options might not know they are inside editor settings.
> 
> As for having it in a single store, i don't think it matters that much, as you don't constantly change it during use, or is it really noticable?

What if we add the tag to search for the commands? I can easily add a component but that's still related to the editor that's why i put everything together. Again, this is a minor thing so if you want i can do the changes.

As per the single store is just that the extension will change over and over. I don't think it will be noticeable but it does makes my finger tingle a bit :smile:

**Comment by SarcevicAntonio** [comment]
we can keep the editor settings in one panel, but add to the suptitle that it includes font settings.

do with the store as you please, i think im fine either way :D

**Comment by paoloricciuti** [comment]
> we can keep the editor settings in one panel, but add to the subtitle that it includes font settings.
> 
> do with the store as you please, i think im fine either way :D

Argh decisions. Ok i'll add to the subtitle and i'll think about the store while we wait for puru to publish the new version

**Review by SarcevicAntonio — APPROVED** [review]
lgtm :)

**Pull request merged**
