### PR TITLE
Upgrade repo to svelte 5 + upgrade template deps to latest

### PR DESCRIPTION
**Pull request by SarcevicAntonio**
plus additional changes:

- remove `'--install',` flag from `svelte-add` command (seems unused)
- rename `five` template to `next`
- removed `ComponentType<SvelteComponent>` types, as they didn't seem to work anymore and i coulnd't find the alternative
- removed the advent of svelte templates (sorry, they don't seem particularly useful and make it so we have to maintain two extra projects)
- upgrade prettier configs and format

### CODE REVIEW

**Review by paoloricciuti — COMMENTED** [review]
LGTM I think you just need to update the engine for the og image from node18 to node20 to unlock the deployment on vercel...p.s. did you also updated the version of svelte we use to 5?

**Comment by SarcevicAntonio** [comment]
yeah we are using svelte 5 for root project and for docs

**Comment by SarcevicAntonio** [comment]
thanks for taking a look! i think i upgraded og image to node 20?

**Comment by paoloricciuti** [comment]
> thanks for taking a look! i think i upgraded og image to node 20?

Yup...let's go!

**Pull request merged**
