### PR TITLE
Added sort order option to the Profile page

### PR DESCRIPTION
**Pull request by K-Sato1995**
addresses: https://github.com/SvelteLab/SvelteLab/issues/244

## Overview

Add the sort-order button to the Profile page.

The default is set to `asc-updated`.

https://github.com/SvelteLab/SvelteLab/assets/32632542/137ca0ed-8e8d-4aa0-96fe-b5b7a2618e0b

### CODE REVIEW

**Comment by paoloricciuti** [comment]
Screenshot_2023-07-23-07-37-30-565_com android chrome

I wonder if in mobile we should make the sort options go to the new line to have a bit more space in general.

**Comment by K-Sato1995** [comment]
@paoloricciuti

Thanks for the feedback! I was thinking the same. Will try it out later!😁

**Comment by paoloricciuti** [comment]
> @paoloricciuti
> 
> Thanks for the feedback! I was thinking the same. Will try it out later!😁

Uh i kinda did it in another pr...merging this now so that i can fix it with a merge back.

**Comment by K-Sato1995** [comment]
@paoloricciuti 

>Uh i kinda did it in another pr...merging this now so that i can fix it with a merge back.

Thanks! Appreciate it!

**Comment by paoloricciuti** [comment]
> @paoloricciuti
> 
> > Uh i kinda did it in another pr...merging this now so that i can fix it with a merge back.
> 
> Thanks! Appreciate it!

Sorry for hijacking your PR...I was fixing some things and I fixed without realizing this PR was still in progress

**Pull request merged**
