### PR TITLE
Add Threlte template

### PR DESCRIPTION
**Pull request by joshnuss**
- Adds Threlte 6 template
- Adds Threlte icon

## Screenshot

image

### CODE REVIEW

**Comment by joshnuss** [comment]
- Template was created using `pnpm create threlte threlte`
- `package-lock.json` was omitted

**Review by SarcevicAntonio — CHANGES_REQUESTED** [review]
Nice one, thank you very much!

One thing that would be needed is for svelte-check to be included in the devDependencies like in the other templates.

We use currently use it to provide errors and warnings in the codemirror editor, so it should be there on every template.

**Comment by joshnuss** [comment]
Thanks @SarcevicAntonio!

I've added the `svelte-check` dependency and a `check` script to run it (copied from basic template).

**Review by SarcevicAntonio — APPROVED** [review]
sweetness!

**Pull request merged**
