### PR TITLE
Add search also for svelte documentation

### LINKED ISSUE #240: ✨ Svelte Docs search
### Describe the problem

Since the new svelte 4 docs page have a search similar to the kit site, we should be able to plug that into SvelteLab similarly.

Maybe we can even unify the search, so you can search both docs in once place.

### Describe the solution you would like

Add a Search Svelte Docs command similar to Search Kit Docs command, or create one unified search Svelte/Kit Docs command.

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by paoloricciuti**
Closes #240 

This adds search also for svelte documentation since now we have a similar json structure for svelte too.

I've made some other modification to allow for this without the need of another search component so now we can pass props to the action component (and i was able to type that in a satisfactory way where if there are no props is not required but if there are it is and you get proper intellisense).

While fiddling with the worker i also imporved a bit the experience avoiding unnecessary fetch to the docs.

### CODE REVIEW

**Comment by SarcevicAntonio** [comment]
Slight thing but the empty state says "search kit docs" regardless of mode

**Review by SarcevicAntonio — COMMENTED** [review]
Didn't take a super close look since I'm away from laptop but looks good

**Comment by paoloricciuti** [comment]
> Slight thing but the empty state says "search kit docs" regardless of mode

Good catch...fixed it

> Didn't take a super close look since I'm away from laptop but looks good so far

Do you prefer to wait? ;)

**Comment by SarcevicAntonio** [comment]
Nah go ahead and merge it 😊

**Pull request merged**
