### PR TITLE
Local Pocketbase and password auth 

### PR DESCRIPTION
**Pull request by SarcevicAntonio**
# motivation

this is the first step of #209

afer this we can add e2e tests (CI)

and then we could think about auto deploy to fly.io & vercel for new PRs and on master merge when tests pass (CD)

# changes

- add migrations and pocketbase setup instuctions
  - note if you review to set .env `POCKETBASE_URL` to local instance
- added password auth to make local setup simpler
- try out new way of handling icons

### CODE REVIEW

**Comment by SarcevicAntonio** [comment]
I think i like this idea around having a central file that defines the icons and just importing that. makes it less of a hassle to deal with and we have a central location that defines what icons we use.

**Comment by paoloricciuti** [comment]
> I think i like this idea around having a central file that defines the icons and just importing that. makes it less of a hassle to deal with and we have a central location that defines what icons we use.

I think this could be good also for reusing icons without importing then a thousand times...a bit of an extra hassle when you have to import a new one but I think it could still be good.

On a quick look this looks great just a quick question: did you wrote the migrations by hand?

Also I know probably noone will ever log via email but I would like a more coherent and captivating design for the login/register page...after all it's an extra click to login and I think someone could actually try to login that way. The current design is not bad at all but I think we can do better. That would also need a way to go back to the homepage in both pages and we should also think on what happens when you try to register with the same email that your GitHub account uses.

**Comment by SarcevicAntonio** [comment]
glad you like the icons thing! ill keep doing it from now and convert all files im touching to the new format

Migrations are autogenerated by pocketbase 💫
I'm not sure how pushing the changes will look yet tho.

good points on the login and register page design! will improve

**Comment by SarcevicAntonio** [comment]
i checked the behaviour of mixing github with password:

- account created with password → can also login via github
- account created with github → cant register because email already taken (clear error message)
  - we could also add password reset so the other behaviour works

**Comment by SarcevicAntonio** [comment]
not sure if the design is up to snuff yet. i added header and logo with link...

**Comment by paoloricciuti** [comment]
> i checked the behaviour of mixing github with password:
> 
> * account created with password → can also login via github
> * account created with github → cant register because email already taken (clear error message)
>   
>   * we could also add password reset so the other behaviour works

Very cool

> not sure if the design is up to snuff yet. i added header and logo with link...

Yeah there's still something off...i think i would like a darker bg...i'll try to see if i can come up with something

**Comment by paoloricciuti** [comment]
> Changing the background from there could be a bit tricky tho 👀

Why?

**Comment by SarcevicAntonio** [comment]
It's not like impossible but im interested to see what you come up with 😁👍

**Comment by SarcevicAntonio** [comment]
can we create an issue for making register/login prettier and get this merged?

**Comment by paoloricciuti** [comment]
> can we create an issue for making register/login prettier and get this merged?

Sure...sorry I forgot about this: merge that down and I'll try to work on the login asap

**Comment by K-Sato1995** [comment]
sweet

**Pull request merged**
